language: node_js

node_js:
  - "10.15.3"

env: 
  - NODE_ENV=test

services:
  - postgresql

before_script:
  - psql -c 'create database banka_test_db;' -U postgres

cache:
  directories:
    - "node_modules"



after_success:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls